# Generated by Django 5.1.3 on 2025-01-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
